
project_id = "syvxflddmryziujvzlxk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326

[realtime]
enabled = true
port = 54327

[functions]
[functions.pet-ai-agent]
verify_jwt = true
